[build]
  base = "frontend"
  command = "npm i -g pnpm && pnpm install --frozen-lockfile=false && pnpm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
